server:
  port: 9999

spring:
  datasource:
    username: test
    password: 123456
    url: jdbc:mysql://localhost:3306/InnovateIT

  # Redis 连接信息
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    com.example: debug